50.times do
  User.create(username: Faker::Name.first_name, password: "1234", league_account: Faker::Name.first_name)
end


Chatroom.create(name: "awesome sauce", capacity: 5)
Chatroom.create(name: "flex peoples", capacity: 10)
Chatroom.create(name: "solo groups", capacity: 7)
Chatroom.create(name: "chilling", capacity: 2)
Chatroom.create(name: "very toxic peeps", capacity: 20)

ChatroomUser.create(user_id: 1, chatroom_id: 1, admin: true)
ChatroomUser.create(user_id: 2, chatroom_id: 2, admin: true)
ChatroomUser.create(user_id: 3, chatroom_id: 3, admin: true)
ChatroomUser.create(user_id: 4, chatroom_id: 4, admin: true)
ChatroomUser.create(user_id: 5, chatroom_id: 5, admin: true)
ChatroomUser.create(user_id: 6, chatroom_id: 1)
ChatroomUser.create(user_id: 7, chatroom_id: 1)
ChatroomUser.create(user_id: 8, chatroom_id: 5)
ChatroomUser.create(user_id: 9, chatroom_id: 5)
ChatroomUser.create(user_id: 10, chatroom_id: 5)
ChatroomUser.create(user_id: 11, chatroom_id: 5)
ChatroomUser.create(user_id: 12, chatroom_id: 4)
ChatroomUser.create(user_id: 13, chatroom_id: 5)
ChatroomUser.create(user_id: 14, chatroom_id: 5)
ChatroomUser.create(user_id: 15, chatroom_id: 5)
ChatroomUser.create(user_id: 16, chatroom_id: 3)
ChatroomUser.create(user_id: 17, chatroom_id: 2)
ChatroomUser.create(user_id: 18, chatroom_id: 3)
ChatroomUser.create(user_id: 19, chatroom_id: 5)
ChatroomUser.create(user_id: 20, chatroom_id: 5)
ChatroomUser.create(user_id: 21, chatroom_id: 5)
ChatroomUser.create(user_id: 22, chatroom_id: 5)
ChatroomUser.create(user_id: 23, chatroom_id: 5)
